export const ACTION_TYPES = {
    STORE_VACCINE: "STORE_VACCINE",
    RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
    LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
    STORE_USER: "STORE_USER",
    CLEAR_STORED_USER: "CLEAR_STORED_USER"
};

export const RESPONSE_STATUS = {
    SUCCESS: 200,
    UNAUTHORIZED: 401
};
